### ISSUE TITLE
Please update the README with the truthiness of ()

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/truthiness-in-ruby-readme#12]
I think the README needs to be updated with the truthiness of the open-and-closed parentheses (). While "", '', [], and {} are all truthy, () is not because it is a NilClass object.

I know that this is a minor issue, but thanks for looking into this.

Sdcrouse

**Comment by cjbrock** [comment]
Hi @Sdcrouse! So generally with these kinds of tutorials, the idea is to communicate the concept of truthiness and falsiness, not to cover comprehensively all the things that can be truthy and falsey in Ruby. Our philosophy is to try to communicate as much information as possible to give a good understanding without completely overwhelming our students. We let the resources section serve as a research guide for when knowing something like that becomes relevant later in a student's career. 
// <3 Corinna

**Comment by Sdcrouse** [comment]
Hi, @cjbrock! That makes a lot of sense. I'll bear that in mind with future tutorials. Thanks for your response!

Sdcrouse
