### ISSUE TITLE
Single bang operator not yet encountered

### ISSUE THREAD

**Issue by caporta** [learn-co-curriculum/truthiness-in-ruby-readme#7]
I think the following copy == false:

>'We've already seen that a "single-bang operator" (!) will negate a boolean value.'

Seems like this is first taught in 'Boolean Operators', which is actually the _subsequent_ module to this one.

**Comment by AnnJohn** [comment]
@SophieDeBenedetto can you check and change the language since Boolean Operators does come afterwards? Due 8/21
